#!/bin/bash


blue(){
    echo -e "\033[34m\033[01m$1\033[0m"
}
green(){
    echo -e "\033[32m\033[01m$1\033[0m"
}
red(){
    echo -e "\033[31m\033[01m$1\033[0m"
}
yellow(){
    echo -e "\033[33m\033[01m$1\033[0m"
}
bred(){
    echo -e "\033[31m\033[01m\033[05m$1\033[0m"
}
byellow(){
    echo -e "\033[33m\033[01m\033[05m$1\033[0m"
}

sd="https://github.com/pymumu/smartdns/releases/download/Release30/smartdns.1.2020.02.25-2212.x86_64-debian-all.deb"

eth_n=$(ip --oneline link show up | grep -v "lo" | awk '{print$2;exit}' | cut -d':' -f1 | cut -d'@' -f1)
loc_ip=$(ip a | grep "$eth_n" | awk '{print $2}' | awk 'END {print}' | cut -d'/' -f1)

pi_wd="4739aedfec7b085af55a29976725a386ad39c9d88f1228c6cffe4ee52971b206"

function install_smartpi(){

cat > /etc/apt/sources.list << EOF
deb http://mirrors.aliyun.com/debian $(cat /etc/os-release | grep VERSION= | cut -d '(' -f2 | cut -d ')' -f1) main
deb http://mirrors.aliyun.com/debian-security $(cat /etc/os-release | grep VERSION= | cut -d '(' -f2 | cut -d ')' -f1)/updates main
deb http://mirrors.aliyun.com/debian $(cat /etc/os-release | grep VERSION= | cut -d '(' -f2 | cut -d ')' -f1)-updates main
EOF

rm -rf /etc/apt/sources.list.d/unstable.list
rm -rf /etc/apt/preferences.d/limit-unstable

apt update && apt install -y sudo locales net-tools dnsutils ipset wget curl git jq unzip ca-certificates haveged subversion rsync apt-transport-https gnupg2 lighttpd
source /etc/profile

wget --no-check-certificate -O ~/smartdns.deb $sd
dpkg -i ~/smartdns.deb

cat << EOF > /etc/smartdns/smartdns.conf
bind :5599
cache-size 20480
#prefetch-domain yes
rr-ttl 86400
#rr-ttl-min 3600
#rr-ttl-max 604800
log-level info
log-file /var/log/smartdns.log
log-size 128k
log-num 2
force-AAAA-SOA yes
server 223.5.5.5
server 119.28.28.28
server 114.114.114.114
server-tcp 223.5.5.5
server-tcp 119.28.28.28
server-tcp 114.114.114.114
EOF

echo "" > /run/smartdns.pid
cat << EOF > /lib/systemd/system/smartdns.service
[Unit]
Description=Smart DNS server
After=network-online.target
Before=nss-lookup.target
Wants=network-online.target
[Service]
Type=forking
PIDFile=/run/smartdns.pid
EnvironmentFile=/etc/default/smartdns
ExecStart=/usr/sbin/smartdns $SMART_DNS_OPTS
KillMode=process
Restart=always
RestartSec=2s
LimitNPROC=1000000
LimitNOFILE=1000000
[Install]
WantedBy=multi-user.target
EOF
rm -rf ~/smartdns.deb

systemctl daemon-reload > /dev/null 2>&1
systemctl enable smartdns > /dev/null 2>&1
systemctl restart smartdns > /dev/null 2>&1


cd ~
mkdir -p /etc/pihole
echo "" > /etc/pihole/adlists.list
cat << EOF > /etc/pihole/setupVars.conf
PIHOLE_INTERFACE=$eth_n
IPV4_ADDRESS=$loc_ip/24
PIHOLE_DNS_1=127.0.0.1#5599
PIHOLE_DNS_2=
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true
BLOCKING_ENABLED=true
WEBPASSWORD=$pi_wd
#DNSMASQ_LISTENING=single
#DNS_FQDN_REQUIRED=true
#DNS_BOGUS_PRIV=true
#DNSSEC=false
#CONDITIONAL_FORWARDING=false
EOF
bash <(wget --no-check-certificate -qO- http://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh) /dev/stdin --unattended

systemctl mask --now dhcpcd > /dev/null 2>&1
systemctl daemon-reload > /dev/null 2>&1

cat << EOF > /etc/pihole/pihole-FTL.conf
PRIVACYLEVEL=0
AAAA_QUERY_ANALYSIS=no
EOF

pihole restartdns



	green " ===========================请重启debian系统=============================="
	green " SmartPi安装完成"
    green " 系统：>=debian9"
    green " Youtube：米月"
    green " 电报群：https://t.me/mi_yue"
    green " Youtube频道地址：https://t.im/n21o"
    green " version：20200304v1"
	green " SmartPi后台地址：http://$loc_ip/admin"
	green " ===========================请重启debian系统=============================="

}


function update_smartdns(){
if test -s /etc/smartdns/smartdns.conf.bak; then
	rm -rf /etc/smartdns/smartdns.conf.bak
	cp /etc/smartdns/smartdns.conf /etc/smartdns/smartdns.conf.bak
	./install -u
	rm -rf /root/smartdns*
fi
wget https://github.com/pymumu/smartdns/releases/download/Release28/smartdns.1.2019.12.15-1028.x86_64-linux-all.tar.gz
tar zxf smartdns.1.2019.12.15-1028.x86_64-linux-all.tar.gz
cd smartdns
chmod +x ./install
./install -i
if test -s /etc/smartdns/smartdns.conf.bak; then
	rm -rf /etc/smartdns/smartdns.conf
	cp /etc/smartdns/smartdns.conf.bak /etc/smartdns/smartdns.conf
fi
systemctl enable smartdns
systemctl restart smartdns
pihole restartdns
	green " ===========================请重启debian系统=============================="
	green " SmartPi更新完成"
    green " 系统：>=debian9"
    green " Youtube：米月"
    green " 电报群：https://t.me/mi_yue"
    green " Youtube频道地址：https://t.im/n21o"
	green " ===========================请重启debian系统=============================="
}

function m_pass(){
    red " =================================="
    red " 修改pi-hole密码"
    red " =================================="
    pihole -a -p
    red " =================================="
    red " pi-hole密码修改完成"
    red " =================================="
}

function rebuil_pi-hole(){
    green " ================================"
    green " 开始重新安装pi-hole"
    green " ================================"
    pihole -r
    green " ================================"
    green " pi-hole安装完成"
    green " ================================"
}

start_menu(){
    clear
    green " ========================================================================"
    green " 简介：debian一键安装SmartPi"
    green " 系统：>=debian9"
    green " Youtube：米月"
    green " 电报群：https://t.me/mi_yue"
    green " Youtube频道地址：https://t.im/n21o"
	green " SmartPi版本：20200303v1"
    green " ========================================================================"
    echo
    green  " 1. 一键安装SmartPi"
	#green  " 2. 一键更新SmartPi"
	green  " 3. 重新安装pi-hole"
	green  " 4. 更改pi-hole密码"
    yellow " 0. 退出脚本"
    echo
    read -p " 请输入数字:" num
    case "$num" in
    1)
    install_smartpi
    ;;
    2)
    update_smartdns
    ;;
	3)
    rebuil_pi-hole 
    ;;
	4)
    m_pass 
    ;;
    0)
    exit 1
    ;;
    *)
    clear
    red "输入的数字不正确，请重新输入"
    sleep 1s
    start_menu
    ;;
    esac
}

start_menu
